---
title: "ffanalytics Visuals"
author: "Tom Kain"
date: "9/5/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(plotly)
library(janitor)
```

```{r import}
week <- 2

projections <-
  here("data", paste0("week",week,"_projections.csv")) %>% 
  read_csv()
```

```{r}

display_df <-
  projections %>% 
  mutate(name = paste0(first_name, " ", last_name)) %>% 
  filter(avg_type == 'robust',
         pos %in% c('WR','RB','TE'),
         tier < 6) %>% 
  mutate(ovrl_rnk = row_number(points %>% desc))

gg <-
  display_df %>% 
  ggplot(aes(points, ovrl_rnk, color=factor(pos))) +
  geom_errorbarh(aes(xmin=floor,xmax=ceiling),height=.75) +
  geom_point(size = 5, color = "white") +
  geom_text(aes(x=points,label=round(points,0)),size=1.75)+
  geom_text(aes(x=ceiling, label=name, hjust=-.2, angle=(0)), size = 1.75)+
  theme(
    plot.background = element_blank()
    ,panel.grid.major.x = element_line(color="grey")
    ,panel.grid.minor.y = element_line(color="grey")
    ,panel.border=element_rect(color="grey",fill=NA)
    ,panel.background = element_blank()
    ,legend.position = "none"
  ) +
  scale_y_reverse() +
  coord_cartesian(xlim = c((min(display_df$floor)-1),
                           (max(display_df$ceiling)+5)))

gg

```