---
title: "Preseason Projection Wrangling"
author: "Tom Kain"
date: "8/13/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

# Resources
1. Fantasy Footballers (UDK)
2. Fantasy Pros (High/Low/Consensus)
3. Yahoo
4. The Athletic

## Fantasy Footballers
```{r}
# here("src", "scrape_fantasy_footballers.R") %>% source()
# result <- get_fantasy_footballers_projections()
result <- here("data", "raw_projections.Rds") %>% readRDS()

projections <-
  result %>% 
  group_by(position, player) %>% 
  summarize_if(is_numeric, mean) %>% 
  mutate(points = 
           (pass_yards / 15) +
           (pass_tds * 4) +
           (ints * -2) +
           (rush_yards / 10) +
           (rush_tds * 6) + 
           (rec * .5) +
           (rec_yards / 10) +
           (rec_tds * 6)
           ) %>% 
  ungroup() %>% 
  mutate_if(is_numeric, round, 0) %>% 
  select(position, player, points, everything()) 

position_point_medians <-
  projections %>% 
  group_by(position) %>% 
  arrange(points %>% desc) %>% 
  mutate(rank = row_number(),
         starter = case_when(
           position %in% c('QB','TE') & rank <= 14 ~ TRUE,
           position %in% c('RB','WR') & rank <= 28 ~ TRUE,
           TRUE ~ FALSE
         )) %>% 
  filter(starter) %>%   
  summarize(median_points = median(points))
  
projections <- 
  projections %>% 
  left_join(position_point_medians, "position") %>% 
  mutate(points_adj = points - median_points)

projections %>% 
  ggplot(aes(points_adj, points, group = position)) +
  geom_point() +
  scale_x_reverse()
  # tiers
  # adp
  # price
```

```{r}
library(BAMMtools)

projections %>% 
  ggplot(aes(points, group = position, color = position)) +
  geom_histogram(bins = 6)

projections %>% 
  filter(position == 'WR') %>% 
  select(points) %>% 
  pull() %>% 
  getJenksBreaks(9)
```

