CREATE TABLE `2021_ff`.`roster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crte_dttm` TIMESTAMP NOT NULL,
  `week` INT NOT NULL,
  `team` VARCHAR(255) NULL,
  `bench` BOOL NOT NULL,
  `slot` VARCHAR(8) NOT NULL,
  `pos` VARCHAR(8) NOT NULL,
  `player` VARCHAR(255) NOT NULL,
  `points` DECIMAL(8,3) NULL,
  `proj` DECIMAL(8,3) NULL,
  `stats` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idroster_UNIQUE` (`id` ASC));
DROP TRIGGER IF EXISTS `2021_ff`.`roster_BEFORE_INSERT`;

DELIMITER $$
USE `2021_ff`$$
CREATE DEFINER = CURRENT_USER TRIGGER `2021_ff`.`roster_BEFORE_INSERT` BEFORE INSERT ON `roster` FOR EACH ROW
BEGIN
SET NEW.crte_dttm = NOW();
END$$
DELIMITER ;